### ISSUE TITLE
Tallylog should not be world writable

### ISSUE THREAD

**Issue by VibroAxe** [1and1internet/ubuntu-18#1]
The docker file command for `chmod 777 -R /var/log` is breaking pam_tally2

When trying to add a user in a downstream image we get the following error
```
pam_tally2: /var/log/tallylog is either world writable or not a normal file
pam_tally2: Authentication error
```

**Comment by VibroAxe** [comment]
Secondly to this , it might be better to use the following rather than making all of the log files executable

`find /var/log -type d -exec chmod 777 {} \;`
`find /var/log -type f ! -name "tallylog" -exec chmod 666 {} \;`

**Comment by brianwilkinson** [comment]
Thanks for raising, I'll look into this. We build these images for our own internal use but this does look like it's unnecessary.

**Comment by brianwilkinson** [comment]
I've uploaded a fix which should hopefully work for you
